
#! /bin/sh

if [ `ls -1 go.mod 2> go.sum` ]; 
then
    echo "The go.mod and go.sum files are already present, no need to run: go mod init"
    go mod tidy
else
    echo "The go.mod and go.sum files are going to be generated by the 'go mod init' command"
    go mod init Log_rocket-Go_GIN_GORM
    go mod tidy
fi

echo "The Go Book Store is ready and the list of books can be accessed at http://localhost:8080/books"
go run main.go
