#! /bin/sh

if [ `ls -1 go.mod 2> go.sum` ]; 
then
    echo "The go.mod and go.sum files are already present, no need to run: go mod init"
    go mod tidy
else
    echo "The go.mod and go.sum files are going to be generated by the 'go mod init' command"
    go mod init github.com/BenWolfaardt/Tuts-Web_Dev-Go_backend/tree/02-Polygot-Frontend_served_in_Go
    go mod tidy
fi

go build
echo "Frontend served in Go - is now going to be hosted on http://localhost:8080"
./02-Polygot-Frontend_served_in_Go