#! /bin/sh

if [ -f go.mod -a -f go.sum  ]; then
    echo ""
    echo "The go.mod and go.sum files are already present, no need to run: go mod init"
    go mod tidy
else
    echo "The go.mod and go.sum files are going to be generated by the 'go mod init' command"
    go mod init BenWolfaardt/helloworld
    go mod tidy
fi

FILE=helloworld
if [ -f "$FILE" ]; then
    echo "The Go binary, $FILE, is already present, no need to run: go build"
else 
    echo "The Go binary, $FILE, is going to be generated by the 'go build' command"
    go build
fi

echo ""
echo "The Hello World App is ready and can be accessed at http://localhost:8080/"
echo ""
echo "Please note:"
echo "   http://localhost:8080/hello can be visited as a route"
echo "   curl http://localhost:8080/api/ping can be performed to perform an API request with JSON"
echo ""
echo "The below is the 'logger' of Gin-Gonic"
echo ""
./helloworld
